 -- task 2
 
 CREATE TABLE SAMPLE_NAME (
                      	id int IDENTITY(1,1) PRIMARY KEY,  
                      	first_name varchar(50), 
                      	last_name varchar(50));

                    
                      
                      INSERT INTO SAMPLE_NAME (first_name, last_name)
                      VALUES ('Irene','Castaneda'), ('Emerald','Holmes'), ('Moses','Spears'), ('Wyatt','Flowers'), ('Slade','Jefferson'), ('Howard','Bender'), 
					  ('Dora','Salinas'), ('Sandra','Barber'), ('Ashely','Taylor'), ('Yoshio','Stephenson'), ('Anika','Oneil'), ('Brenna','Burke'), 
					  ('Leigh','Hayden'), ('Bianca','Rivera'), ('Morgan','Clark'), ('Meredith','Acosta'), ('Adara','Chapman'), ('Jordan','Duran'), 
					  ('Channing','Newman'), ('Quin','Russo'), ('Damian','Snider'), ('Mason','Myers'), ('Demetrius','Cook'), ('Wylie','Mason'), ('Axel','Britt'), 
					  ('Oren','Johnson'), ('Scott','Burgess'), ('Shafira','Mcconnell'), ('Kellie','Head'), ('Raja','Chen'), ('Rigel','Sheppard'), 
					  ('Isabelle','Emerson'), ('Kaseem','Santiago'), ('Naomi','Ingram'), ('Barclay','York'), ('Trevor','Molina'), ('Reece','Oneil'), 
					  ('Hakeem','Cameron'), ('Daniel','Lawson'), ('Amal','Romero'), ('Eliana','Wiggins'), ('Gemma','Valenzuela'), ('Diana','Sparks'), 
					  ('Angelica','Sosa'), ('Dillon','Howell'), ('Rhoda','Levine'), ('Silas','Bradley'), ('Zephr','Mcdowell'), ('Whitney','Calhoun'), 
					  ('Harper','Sykes'), ('Hiram','Young'), ('Zelda','Carney'), ('Candace','Meadows'), ('Micah','England'), ('Ruth','Malone'), ('Nicole','Terry'), 
					  ('Palmer','Sandoval'), ('Reagan','Kim'), ('Holly','Goodman'), ('Demetria','Gonzales'), ('Sacha','Silva'), ('Devin','Morrison'), 
					  ('Adele','Tucker'), ('Solomon','Franklin'), ('Nerea','Stephenson'), ('Jerome','Rosa'), ('Gil','Hansen'), ('Idola','Ray'), ('Harding','Farley'), 
					  ('Harriet','Stuart'), ('Kyle','Williams'), ('Owen','Douglas'), ('Cain','Brock'), ('Harper','Moody'), ('Maia','Swanson'), ('Seth','Gilliam'), 
					  ('Bernard','Forbes'), ('Destiny','Powers'), ('Joseph','Banks'), ('Callie','Boyle'), ('Howard','Dejesus'), ('Griffin','Stokes'), 
					  ('Cora','Delacruz'), ('Todd','Mercer'), ('Sybill','Freeman'), ('Liberty','Black'), ('Wayne','Beasley'), ('Sophia','Dean'), 
					  ('Jerome','Cunningham'), ('Gil','Rowland'), ('Aileen','Roth'), ('Igor','Marshall'), ('Quinn','Marshall'), ('Keely','Richardson'), 
					  ('Charlotte','Quinn'), ('Curran','Barker'), ('Ayanna','Warner'), ('Hasad','Mckay'), ('Ebony','Aguilar'), ('Kevin','Haynes'), ('Hector','Warren'), 
					  ('Jarrod','Paul'), ('Emmanuel','Dyer'), ('Tarik','Burris'), ('Mark','Burris'), ('Nasim','Oneal'), ('Keiko','Schultz'), ('Nash','Harrison'), 
					  ('Hashim','Mcneil'), ('Vance','Odonnell'), ('Jenette','Norton'), ('Jerome','Robinson'), ('Halee','Parker'), ('Rhea','Wise'), ('Hyacinth','Mueller'), 
					  ('Echo','Lucas'), ('Holmes','Hess'), ('Kasimir','Joyce'), ('Dominique','Jacobson'), ('Briar','May'), ('Christian','Nash'), ('Serena','Fuller'), 
					  ('Reuben','Blair'), ('Imelda','Sullivan'), ('George','Campos'), ('MacKenzie','Cote'), ('Asher','Maynard'), ('Kenyon','Bass'), ('Nissim','Carroll'), 
					  ('Mia','Hays'), ('Chaney','Bean'), ('Maggie','Clemons'), ('Chadwick','Scott'), ('Ashton','Merritt'), ('Erin','Mcfarland'), ('Hayfa','Sharp'), 
					  ('August','Manning'), ('Chaney','Allen'), ('Natalie','Hancock'), ('Shay','Little'), ('Zia','Roy'), ('Selma','Dodson'), ('Jerry','Molina'), 
					  ('McKenzie','Hodge'), ('Angelica','Alford'), ('Henry','Roberson'), ('Jin','Williamson'), ('Jameson','Bauer'), ('Aiko','Massey'), ('Kadeem','Moses'), 
					  ('Vivien','Baker'), ('Shelly','Leach'), ('Sarah','Butler'), ('Kelsie','Duran'), ('Zenia','Barlow'), ('Jocelyn','Johns'), ('Brenda','Robinson'), 
					  ('Jameson','Mooney'), ('Owen','Acevedo'), ('Ezra','Abbott'), ('Carly','Collier'), ('Savannah','Burns'), ('Aidan','Mcdowell'), ('Baker','Johns'), 
					  ('Duncan','Robles'), ('Keely','Hubbard'), ('Stella','Valencia'), ('Gray','Fuller'), ('Constance','Harrell'), ('Cora','Nash'), ('Andrew','Ayers'), 
					  ('Britanni','Ingram'), ('Selma','Bradford'), ('Charlotte','Preston'), ('Emi','Perry'), ('Noelani','Doyle'), ('Cameron','Dunn'), ('Jordan','Jenkins'), 
					  ('Ira','Wilder'), ('Sebastian','Velazquez'), ('Ariel','Spence'), ('Tate','Greer'), ('Liberty','West'), ('Tana','Meyers'), ('Lucius','Welch'), 
					  ('Constance','Best'), ('Xyla','Horne'), ('Justine','Rice'), ('Medge','Holcomb'), ('Jael','Lang'), ('Inga','Bond'), ('August','Collier'), 
					  ('Brandon','Duffy'), ('Uriah','Harding'), ('Bo','Shelton'), ('Deirdre','Perry'), ('Caesar','Salazar'), ('Curran','Bradley'), ('Wade','Thomas'), 
					  ('Darryl','Michael'), ('Tasha','Watts'), ('Carly','Thomas'), ('Kalia','Gilmore'), ('Nadine','Donaldson'), ('Tamara','Allen'), ('Aiko','Pennington'), 
					  ('Kaye','Bishop'), ('Jason','Reilly'), ('Katell','Hyde'), ('Ainsley','Gould'), ('Jada','Harris'), ('Denton','Bell'), ('Byron','Cash'), 
					  ('Sade','Tyson'), ('Maya','James'), ('Christen','Pitts'), ('Graiden','Barrera'), ('Philip','Douglas'), ('Scott','Dalton'), ('John','Pittman'), 
					  ('Christen','Hurley'), ('Ishmael','Henson'), ('Nigel','Clay'), ('Fredericka','Valentine'), ('Timon','Boone'), ('Zia','Witt'), ('Jakeem','Price'), 
					  ('Gwendolyn','Jarvis'), ('Maxine','Alston'), ('Hilary','Ford'), ('Moana','Becker'), ('Ferdinand','Mcguire'), ('Addison','Sawyer'), ('Maxine','Trevino'), 
					  ('Flavia','Bolton'), ('Maggie','Lott'), ('Hedley','Oconnor'), ('Abel','Stewart'), ('Sebastian','Shaw'), ('Laurel','Acosta'), ('Quinn','Rodriguez'), 
					  ('Destiny','Best'), ('Burke','Kim'), ('Hector','Finch'), ('Ria','Fields'), ('Craig','Sheppard'), ('Brody','Sanford'), ('Joy','Stout'), ('Axel','Carey'), 
					  ('Levi','Head'), ('Macaulay','Montoya'), ('Hillary','Macias'), ('Kyla','Wiley'), ('Armando','Chang'), ('Cheryl','Barr'), ('Jeanette','Rivera'), 
					  ('Kato','Tyson'), ('Risa','Wilder'), ('Isaac','Clarke'), ('Kirk','Lambert'), ('Aphrodite','Carson'), ('Jermaine','Avila'), ('Hunter','Cortez'), 
					  ('Isabelle','Lawson'), ('Mark','Roy'), ('Freya','Guthrie'), ('Joseph','Noel'), ('Curran','Church'), ('Deacon','Maxwell'), ('Cameron','Bray'), 
					  ('Jameson','Nixon'), ('Bevis','Sears'), ('Jelani','Dillon'), ('Quail','Vaughn'), ('Elijah','Duffy'), ('Ciaran','Buchanan'), ('Xandra','Kemp'), 
					  ('Cheryl','Rocha'), ('Shaeleigh','Dillon'), ('Larissa','Martinez'), ('Fredericka','Bender'), ('MacKenzie','Miles'), ('Sarah','Walters'), 
					  ('Octavius','Leonard'), ('Reese','Chandler'), ('Martin','Barnett'), ('Jasmine','Rich'), ('Tatiana','Tran'), ('Quinlan','Ingram'), ('Ashton','Mills'), 
					  ('Jaquelyn','Estes'), ('Paula','Hancock'), ('Sandra','West'), ('Aspen','Herrera'), ('Abigail','Lee'), ('Cade','Stevens'), ('Serena','Steele'), 
					  ('Ayanna','Grimes'), ('Timon','Turner'), ('Kadeem','Guthrie'), ('Hayden','Barker'), ('Noah','Newman'), ('Brett','Salazar'), ('Jonas','Flowers'), 
					  ('Dolan','Wiggins'), ('Miriam','Fletcher'), ('Curran','Wiley'), ('Zia','Arnold'), ('Quentin','Schroeder'), ('Jerry','Bowers'), ('Arsenio','House'), 
					  ('Savannah','Frank'), ('Myles','Mann'), ('William','Bailey'), ('Vance','Bond'), ('Griffin','Mathis'), ('Cheryl','Weber'), ('Lars','White'), 
					  ('Yvonne','Wilkinson'), ('Beverly','Wise'), ('Ryder','Harvey'), ('Rhonda','Vega'), ('Brock','Howell'), ('Rashad','Saunders'), ('Lacota','Curry'), 
					  ('Amal','Hull'), ('Berk','Ramos'), ('Kessie','Dyer'), ('Bethany','Hart'), ('Beau','Mcdaniel'), ('Emery','Stark'), ('Trevor','Bolton'), 
					  ('Morgan','Walls'), ('Beverly','Hopper'), ('Echo','Carter'), ('Carolyn','Hensley'), ('Hadley','Charles'), ('Laura','Merritt'), ('Bruno','Holt'), 
					  ('Eagan','Bradley'), ('Brady','Russell'), ('Theodore','Petersen'), ('Sylvia','Heath'), ('Cara','Mercado'), ('Gregory','Meadows'), ('Vladimir','Guthrie'), 
					  ('Chandler','Bowers'), ('Stephen','Mckee'), ('Minerva','Barrera'), ('Steven','Taylor'), ('Ian','Bryant'), ('Ulla','Barron'), ('Angela','Sparks'), 
					  ('Quyn','Bonner'), ('Samson','Coffey'), ('Clark','Conway'), ('Arsenio','Hartman'), ('Sawyer','Mcguire'), ('Galena','Cooley'), ('Uma','Reyes'), 
					  ('Elijah','Watkins'), ('Elizabeth','Bruce'), ('Roth','Warren'), ('Harriet','Chan'), ('Norman','Atkins'), ('Kevin','Garner'), ('Edan','Roman'), 
					  ('Rama','Dixon'), ('Bernard','Lancaster'), ('Lewis','Bradley'), ('Adam','Huff'), ('Colin','Hale'), ('Shannon','Barron'), ('Malachi','Stein'), 
					  ('Marcia','Strong'), ('Dalton','Albert'), ('Destiny','Nixon'), ('Travis','Knox'), ('Karly','Stewart'), ('Alana','Russell'), ('Raven','Solis'), 
					  ('Mallory','Mayo'), ('Walter','Austin'), ('Benedict','Kirby'), ('Dorian','Tate'), ('Melanie','Trevino'), ('Cailin','Robles'), ('Kessie','Nichols'), 
					  ('Chester','Garza'), ('Garrett','Myers'), ('Serena','Kelly'), ('Katelyn','Wright'), ('Tate','Stout'), ('Josiah','Bell'), ('Benedict','Richardson'), 
					  ('Maggy','Brennan'), ('Maite','Puckett'), ('Austin','Ball'), ('Cathleen','Chen'), ('Cairo','Mills'), ('Minerva','Galloway'), ('Jorden','Mcgowan'), 
					  ('Leandra','Odom'), ('Brenna','Serrano'), ('Nevada','Hobbs'), ('Ahmed','Albert'), ('Donna','Reeves'), ('Meredith','Bryan'), ('Bruce','Dale'), 
					  ('Medge','Yang'), ('Phillip','Marshall'), ('Ila','Bishop'), ('Charde','Casey'), ('Deirdre','Thompson'), ('Harlan','Hogan'), ('Dominique','Barry'), 
					  ('Flavia','Hamilton'), ('Dean','Phillips'), ('Kessie','Dejesus'), ('Daquan','Vance'), ('Francesca','Mcneil'), ('Odessa','Ross'), ('Kylie','Howard'), 
					  ('Nerea','Sharpe'), ('Caldwell','Snider'), ('Ray','Shaffer'), ('Mallory','Sims'), ('Solomon','Burgess'), ('Xaviera','Suarez'), ('Katelyn','Combs'), 
					  ('Jin','Britt'), ('Dale','Olson'), ('Uma','Terry'), ('Hector','Shaw'), ('Kessie','House'), ('Selma','Knapp'), ('Kenneth','Bolton'), ('Arthur','Flynn'), 
					  ('Aretha','Brown'), ('Phillip','Faulkner'), ('Germaine','Rush'), ('Quail','Mcfadden'), ('Briar','Aguilar'), ('Sylvia','Andrews'), ('Meredith','Sellers'), 
					  ('Elliott','Bird'), ('Yvonne','Hebert'), ('Naida','Massey'), ('Asher','Elliott'), ('Marah','Foley'), ('Raymond','Glenn'), ('Armand','Doyle'), 
					  ('Thor','Potter'), ('Oprah','Mccarthy'), ('Malachi','Bowen'), ('Magee','Jennings'), ('Audra','Dillon'), ('Lewis','Hooper'), ('Caldwell','Sears'), 
					  ('Zane','Townsend'), ('Brittany','Richmond'), ('Kellie','Cole'), ('Slade','Buck'), ('Quinlan','Sherman'), ('Thane','Chambers'), ('Kimberly','Dickson'), 
					  ('Nash','Crawford'), ('Shelley','English'), ('Porter','Huber'), ('Nomlanga','Stein'), ('Travis','Davis'), ('Timothy','Duffy'), ('Ferris','Ward'), 
					  ('Oren','Gutierrez'), ('James','Dyer'), ('Cody','Lynn'), ('Aimee','Gill'), ('Rigel','Kirkland'), ('Wilma','Sharpe'), ('Neville','Thornton'), 
					  ('Hedwig','Parrish'), ('Quynn','Montgomery'), ('Kameko','Boyle'), ('Kiona','Carr'), ('Rowan','Jackson'), ('Bo','Shields'), ('Clio','Mason'), 
					  ('Samuel','Nielsen'), ('Vielka','Stephenson'), ('Thor','Mooney'), ('Hanae','Kramer'), ('Jermaine','Rollins'), ('Yael','Bauer'), ('Herman','Gaines'), 
					  ('Garrett','Hansen'), ('McKenzie','Cook'), ('Genevieve','Snyder'), ('Camille','Wilkins'), ('Ezra','Goodwin'), ('Frances','Merrill'), 
					  ('Ruby','Mercado'), ('Molly','Ramsey'), ('Claudia','Barrera'), ('Acton','Hansen'), ('Dara','Clayton'), ('Orlando','Joyner'), ('Duncan','Abbott'), 
					  ('Jakeem','Hopper'), ('Charlotte','Kirk'), ('Emerson','Cooke'), ('Amos','Best'), ('Dexter','Perry'), ('Aquila','Pickett'), ('Remedios','Bridges'), 
					  ('Yen','Hanson'), ('Katelyn','Parker'), ('Alyssa','Cleveland'), ('Carly','Charles'), ('Maggie','Garcia'), ('Ira','Mccarthy'), ('Charity','Berger'), 
					  ('Maite','Ray'), ('Nichole','Norman'), ('Brenna','Harrison'), ('Wang','Michael'), ('Lillian','Moore'), ('Leandra','Burton'), ('Reagan','Adams'), 
					  ('Xena','Bridges'), ('Ivor','Stone'), ('Alika','Browning'), ('Preston','Matthews'), ('Isaiah','Newman'), ('Keith','Pitts'), ('Keegan','Nolan'), 
					  ('Alika','Castillo'), ('Tatyana','Hunt'), ('Reed','Glass'), ('Gail','Hampton'), ('Thaddeus','Briggs'), ('Arden','Swanson'), ('Howard','Silva'), 
					  ('Herman','Meadows'), ('Christine','Gibbs'), ('Leonard','Gross'), ('Aristotle','Hodges'), ('Alyssa','Webster'), ('Donovan','Steele'), 
					  ('Jessica','Calderon'), ('Gloria','Hammond'), ('Melanie','Kramer'), ('Hector','Gardner'), ('Jessica','Faulkner'), ('Barclay','Smith'), 
					  ('Berk','Hyde'), ('Karen','Knapp'), ('James','Weber'), ('Bruno','Hernandez'), ('Darius','Moody'), ('Lacota','Berger'), ('Melodie','Duffy'), 
					  ('Emmanuel','Hartman'), ('Seth','Morin'), ('Erich','Hutchinson'), ('Hector','Gallegos'), ('Carol','Vazquez'), ('Cherokee','Herrera'), 
					  ('Abdul','Pollard'), ('Kasper','Wolf'), ('Xenos','Boyer'), ('Octavia','Wilkins'), ('Ivor','Arnold'), ('Cailin','Craft'), ('Lisandra','Vaughan'), 
					  ('Sonya','Le'), ('Kerry','Joseph'), ('Ria','Morris'), ('Medge','Velazquez'), ('Buffy','Horton'), ('Hilary','Soto'), ('Adrian','Morse'), 
					  ('Claudia','Ortiz'), ('Marcia','Cardenas'), ('Cailin','Graves'), ('Gary','Gallagher'), ('Josiah','Watson'), ('Vaughan','Wheeler'), 
					  ('Rhiannon','Glenn'), ('Andrew','Gilmore'), ('Rhea','Ewing'), ('Jordan','Meadows'), ('Erasmus','Dixon'), ('Kuame','Tucker'), ('Hillary','Riggs'), 
					  ('Tanek','Hess'), ('Gannon','Hendrix'), ('Wang','Berger'), ('Seth','Grant'), ('Lucas','Barton'), ('Castor','Singleton'), ('Kato','Faulkner'), 
					  ('Roth','Tillman'), ('Yardley','Moon'), ('Quon','England'), ('Charlotte','Cherry'), ('Maggie','Pate'), ('Sasha','Hamilton'), ('Judah','Oneal'), 
					  ('Keelie','Riley'), ('Mohammad','Montgomery'), ('Ramona','King'), ('Basia','Rivas'), ('Astra','Wade'), ('Chastity','Jefferson'), ('Deanna','Clarke'), 
					  ('Tatum','Sanders'), ('Ciara','Nixon'), ('Melinda','Keller'), ('Carter','Hampton'), ('Jacob','Mays'), ('Murphy','Miles'), ('Hilda','Kemp'), 
					  ('Grant','Harrison'), ('Axel','Mcconnell'), ('Ralph','Le'), ('Jasper','Mccoy'), ('Lee','Bolton'), ('Grant','Sears'), ('Ivan','Puckett'), 
					  ('Sydnee','Mathis'), ('Lunea','Christian'), ('Avye','Finley'), ('Oliver','Manning'), ('Nyssa','Pacheco'), ('Hermione','Thomas'), ('Madeson','Craig'), 
					  ('Ian','Beasley'), ('Lucas','Henry'), ('MacKenzie','Robles'), ('Raven','Mccall'), ('Eagan','Burt'), ('Samuel','Garrett'), ('Zeus','Garcia'), 
					  ('Ray','Martinez'), ('Buffy','Armstrong'), ('Elijah','Benton'), ('Alana','Sloan'), ('Daryl','Salinas'), ('Kaye','Whitfield'), ('Todd','Walker'), 
					  ('Ira','Williamson'), ('Michelle','Barry'), ('Burke','Chase'), ('Iona','Hicks'), ('Vance','Tran'), ('Jael','Molina'), ('Daryl','Nicholson'), 
					  ('Mason','Price'), ('Otto','Cabrera'), ('Charde','Ross'), ('Madeline','Wade'), ('Burton','Randall'), ('Kasper','Griffith'), ('Sade','Sellers'), 
					  ('Tiger','Lyons'), ('Sara','Cochran'), ('Ingrid','Ramirez'), ('Flavia','Pacheco'), ('Phelan','Harmon'), ('Shay','Henson'), ('Yuri','Hyde'), 
					  ('George','Townsend'), ('Bruce','Raymond'), ('Octavius','Mitchell'), ('Mariam','Lambert'), ('Arthur','Roberts'), ('Noel','Garner'), 
					  ('Noelani','Estrada'), ('Lucas','Marquez'), ('Nichole','Fernandez'), ('Hasad','Little'), ('Abigail','Bennett'), ('Cailin','Wells'), 
					  ('Germane','Mcmahon'), ('Eliana','Barnett'), ('Ivan','Whitney'), ('Candice','Walls'), ('Dale','Dodson'), ('Kelsey','Mullins'), ('Nola','Barnett'), 
					  ('Katell','Craft'), ('Odysseus','Merritt'), ('Brandon','Wilkins'), ('Aileen','Duke'), ('Theodore','Holt'), ('Cruz','Mcmahon'), ('Melyssa','Thornton'), 
					  ('Cecilia','Miller'), ('Eugenia','Fernandez'), ('Thane','Mccarty'), ('Hedley','Blackwell'), ('Larissa','Cooley'), ('Kuame','Vasquez'), 
					  ('Blossom','Powell'), ('Samuel','Vinson'), ('Walter','Britt'), ('Peter','Ramos'), ('Charlotte','Lane'), ('Judah','Hammond'), ('Sopoline','Swanson'), 
					  ('Tyrone','Wynn'), ('Basil','Riggs'), ('Hu','Malone'), ('Keegan','Blair'), ('Deanna','Chase'), ('Quinlan','Barron'), ('Daniel','King'), 
					  ('Jamal','Klein'), ('Lael','Cameron'), ('Jelani','Eaton'), ('Ginger','Fuller'), ('Nicole','Taylor'), ('Brent','Harmon'), ('Kevin','Peck'), 
					  ('Steven','Anthony'), ('Gwendolyn','Washington'), ('Leigh','Cortez'), ('Donovan','Cervantes'), ('Oliver','Key'), ('Kevin','Pierce'), 
					  ('Zeph','Harrington'), ('Cassady','Howell'), ('Jordan','Sweeney'), ('Stephen','Mejia'), ('Walker','Gallegos'), ('Quentin','Sims'), ('Jena','Baldwin'), 
					  ('Sydnee','Rivers'), ('Benjamin','Buckner'), ('Whitney','Calhoun'), ('Wang','Delgado'), ('Lucian','Jenkins'), ('Venus','Powers'), ('Paki','Christian'), 
					  ('Quintessa','Christian'), ('Uta','Gilmore'), ('Orson','Barron'), ('Julian','Collins'), ('Kelsie','Mccoy'), ('Kelsey','Mann'), ('Sybill','Haley'), 
					  ('Ryder','Bartlett'), ('Micah','Oneil'), ('Oren','Rios'), ('Kalia','Livingston'), ('Hammett','Crawford'), ('Sonia','Boyer'), ('Cheyenne','Pena'), 
					  ('Catherine','Harrison'), ('Constance','Downs'), ('Aladdin','Parsons'), ('Allegra','Weeks'), ('Velma','Mitchell'), ('Camilla','Burns'), ('Catherine','Carpenter'), 
					  ('Clinton','Gonzalez'), ('Daquan','Henry'), ('Illiana','Fitzpatrick'), ('Quemby','Valentine'), ('Hollee','Holcomb'), ('Benedict','Hooper'), ('Colleen','Sawyer'), 
					  ('Susan','Workman'), ('Kylee','Spence'), ('Caesar','Nicholson'), ('Drake','Stevenson'), ('Lillith','Mooney'), ('Kyle','Frank'), ('Indira','Kelley'), 
					  ('Quyn','Spears'), ('Ryder','Osborne'), ('Vivian','Mcintyre'), ('Sawyer','Kaufman'), ('Tamekah','Ayala'), ('Norman','Dodson'), ('Stacy','Henry'), ('Emery','Fox'), 
					  ('Daquan','Berg'), ('Idola','Banks'), ('Carlos','Kirk'), ('Candice','Hess'), ('Buckminster','Williamson'), ('Salvador','Baker'), ('Armando','Salas'), 
					  ('Zenia','Perez'), ('Quinlan','Holland'), ('Chloe','Morton'), ('Portia','Ellis'), ('Virginia','Sweet'), ('Jamal','Golden'), ('Colton','Chan'), ('Abra','Gill'), 
					  ('Keane','Gaines'), ('Nissim','Tucker'), ('Jacob','Acosta'), ('Beau','Mayo'), ('Gavin','Coffey'), ('Darrel','Barnett'), ('Pascale','Jefferson'), 
					  ('Bradley','Estrada'), ('Brenna','Noble'), ('Bernard','Mason'), ('Judith','Buck'), ('Wade','Hubbard'), ('Hedy','Walsh'), ('Gemma','Battle'), ('Channing','White'), 
					  ('Karly','Mckenzie'), ('Zenaida','Baird'), ('Daquan','Mann'), ('George','Pitts'), ('Jemima','Patton'), ('Lester','Mckinney'), ('Abigail','Johnson'), 
					  ('Isabella','Guzman'), ('Hadassah','Mcclure'), ('Reese','Meyers'), ('Hedley','Wolfe'), ('Jenna','Rosa'), ('Raja','Cardenas'), ('Karly','Beasley'), 
					  ('Bert','Chaney'), ('Suki','Sweet'), ('Kirk','Foreman'), ('Wylie','Rodriguez'), ('Cassidy','Wilder'), ('Rahim','Mercado'), ('Gareth','Nguyen'), ('Mary','Aguirre'), 
					  ('Aimee','Griffith'), ('Macy','Butler'), ('Justina','Middleton'), ('Kareem','Stark'), ('Germane','Schwartz'), ('Herman','Tyler'), ('Kenyon','Gardner'), 
					  ('Sharon','Fields'), ('Inez','Bright'), ('Olympia','Mclean'), ('Blythe','Holmes'), ('Omar','Willis'), ('Emily','Miles'), ('Aphrodite','Blanchard'), ('Inga','Ward'), 
					  ('Vanna','Holloway'), ('Kiara','Hicks'), ('Reece','Stout'), ('Eagan','Pruitt'), ('Price','Holt'), ('Grace','Mitchell'), ('Karyn','Melton'), ('Jacqueline','Fisher'), 
					  ('Hashim','Gallegos'), ('Kimberly','Glenn'), ('Mark','Butler'), ('Leroy','Pearson'), ('William','Bishop'), ('Heidi','Wilson'), ('Howard','Haley'), 
					  ('Britanni','Waters'), ('Quentin','Rivera'), ('Claire','Dalton'), ('Keiko','Bender'), ('Ila','Bridges'), ('Boris','Nelson'), ('Ciaran','Bryant'), 
					  ('Kermit','Medina'), ('Nolan','Rocha'), ('Hanna','Ballard'), ('Abbot','Avila'), ('Dexter','Rivera'), ('Hector','Coffey'), ('Ivory','Hayes'), ('Xantha','Meadows'), 
					  ('Warren','Gaines'), ('Owen','Hatfield'), ('Celeste','Ortega'), ('Lilah','Pate'), ('Forrest','Hewitt'), ('Craig','Bradley'), ('Hedwig','Burke'), ('Ivory','Paul'), 
					  ('Jared','Bennett'), ('Mallory','Buck'), ('Christine','Hendrix'), ('Gregory','Townsend'), ('Ulric','Berger'), ('Tad','Hutchinson'), ('Kadeem','Dotson'), 
					  ('Nadine','Pratt'), ('Jaden','Schneider'), ('Damian','Dunn'), ('Kennan','Griffin'), ('Rashad','Burris'), ('Illana','Yates'), ('May','Fulton'), ('Venus','Pope'), 
					  ('Cairo','Buckner'), ('Ocean','Chandler'), ('Jared','Booker'), ('Bruno','Mullins'), ('Walker','Mccarthy'), ('Denton','Mcdonald'), ('Noel','Mccall'), 
					  ('Ava','Mccoy'), ('Curran','Fox'), ('Ray','French'), ('Skyler','Hogan'), ('Octavia','Fulton'), ('Haviva','Walsh'), ('Imelda','Mann'), ('Lane','Wilkinson'), 
					  ('Brady','Carey'), ('Destiny','Marsh'), ('Dustin','Mercer'), ('Colin','Buckley'), ('Madaline','Pollard'), ('Glenna','Bender'), ('Ocean','Padilla'), 
					  ('Fallon','Conrad'), ('Hyatt','Cervantes'), ('Yeo','Paul'), ('Mollie','Oneil'), ('Cairo','Mays'), ('Rigel','Bell'), ('Kieran','Park'), ('Samson','Robinson'), 
					  ('Lucas','Roth'), ('Shelley','Dominguez'), ('Cheyenne','Peck'), ('Ariel','Black'), ('Dennis','Russo'), ('Alice','Pitts'), ('Leo','Andrews'), ('Herman','Barlow'), 
					  ('Ignatius','Tanner'), ('Raphael','Burgess'), ('Kato','Castro'), ('Whoopi','Finch'), ('Flynn','Pruitt'), ('Xander','Church'), ('Josiah','Butler'), 
					  ('Anastasia','Pearson'), ('Cassandra','William'), ('Ulysses','Little'), ('Ivan','Gallagher'), ('Clio','Jimenez'), ('Magee','David'), ('Tobias','Trujillo'), 
					  ('Sean','Rojas'), ('Gwendolyn','Eaton'), ('Deacon','Rivers'), ('Mohammad','Coleman'), ('Gavin','Mathis'), ('Rigel','Foley'), ('Honorato','Jimenez'), 
					  ('Logan','Flores'), ('Louis','Buckner'), ('Doris','Long'), ('Cole','Buck'), ('Rajah','Underwood'), ('Chancellor','Rice'), ('Mariam','Parks'), ('Bevis','Allen'), 
					  ('Cole','Ball'), ('Maggy','Cardenas'), ('Benedict','Holloway'), ('Sybill','Galloway'), ('Ferdinand','Hull'), ('Marny','Dorsey'), ('Maia','Shepherd'), 
					  ('Jeremy','Yang'), ('Trevor','Pace'), ('Tobias','Randall'), ('Serena','Mcconnell'), ('Nigel','Morris'), ('Jane','Lambert'), ('TaShya','Bridges'), ('Eric','Peck'), 
					  ('Logan','Davenport'), ('Lavinia','Stout'), ('Amelia','Case'), ('Jasper','Logan'), ('Basil','Shaffer'), ('Owen','Lee'), ('Leah','Greene'), ('Louis','Bonner'), 
					  ('Mohammad','Tate'), ('Melvin','Marshall'), ('Timothy','Hammond');



SELECT TOP 1000000
      sn1.[First_Name],
	  sn2.[Last_Name]
  FROM [dbo].[SAMPLE_NAME] sn1
CROSS JOIN
SAMPLE_NAME sn2;



/*task 3
CTE используется, когда нам нужно создать временную таблицу, которую мы можем использовать в запросе несколько раз, обращаясь к ней по присвоенному имени. 
В этом отличие от подзапроса. Чтобы использовать подзапрос, его нужно полностью копировать туда, где мы хотим его использовать.